# Generated by Django 6.0.8 on 2026-08-19 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('default_coffee_type', models.CharField(choices=[('arabica', 'Arabica'), ('robusta', 'Robusta')], max_length=20)),
                ('default_grade', models.CharField(blank=True, max_length=50)),
                ('default_source', models.CharField(blank=True, max_length=250)),
                ('default_process', models.CharField(blank=True, max_length=50)),
                ('default_foreign_smell', models.CharField(blank=True, default='None', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('is_acquired_client', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_stage', models.CharField(choices=[('new_lead', 'New Lead'), ('sample_sent', 'Sample Sent'), ('sample_received', 'Sample Received'), ('followup', 'Follow-up'), ('negotiation', 'Negotiation'), ('contract_signed', 'Contract Signed'), ('recurring_supply', 'Recurring Supply'), ('lost', 'Lost')], default='new_lead', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=20)),
                ('object_id', models.CharField(max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('coffee_type', models.CharField(choices=[('arabica', 'Arabica'), ('robusta', 'Robusta')], max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=250)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('process', models.CharField(blank=True, max_length=50)),
                ('season_of_harvest', models.CharField(blank=True, max_length=100)),
                ('foreign_smell', models.CharField(blank=True, max_length=50)),
                ('foreign_matter', models.CharField(blank=True, max_length=50)),
                ('prints', models.CharField(blank=True, max_length=50)),
                ('physical_damages', models.CharField(blank=True, max_length=10)),
                ('defects', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity_after_sorting', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=150)),
                ('verified_by', models.CharField(blank=True, max_length=250)),
                ('delivered_by', models.CharField(blank=True, max_length=150)),
                ('car_number', models.CharField(blank=True, max_length=50)),
                ('received_by', models.CharField(blank=True, max_length=150)),
                ('stage', models.CharField(choices=[('green_received', 'Green Bean Received'), ('stored', 'Stored'), ('roasted', 'Roasted'), ('ground', 'Ground'), ('packaged', 'Packaged')], default='green_received', max_length=30)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='web.coffeevariety')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_weight', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('delivery_status', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='in_transit', max_length=30)),
                ('courier_name', models.CharField(default='DHL', max_length=50)),
                ('tracking_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coffee_stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.coffeestock')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.company')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_alert_sent_at', models.DateTimeField(blank=True)),
                ('day_3_guide_sent_at', models.DateTimeField(blank=True, null=True)),
                ('day_7_contract_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_converted_to_contract', models.BooleanField(default=False)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume_per_cycle_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('montly', 'monthly')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signed_name', models.CharField(blank=True, max_length=150)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('next_delivery_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.company')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('interested_in_contract', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.sample')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Stock Received'), ('sample', 'Sample Taken'), ('roast_input', 'Sent for Roasting'), ('roast_output', 'Roasted Output'), ('grind_input', 'Sent for Grinding'), ('grind_output', 'Ground Output'), ('package_input', 'Sent for Packaging'), ('package_output', 'Packaged Output'), ('dispatch', 'Dispatched'), ('loss', 'Loss / Waste'), ('adjustment', 'Inventory Adjustment')], max_length=30)),
                ('from_stage', models.CharField(blank=True, choices=[('green_received', 'Green Bean Received'), ('stored', 'Stored'), ('roasted', 'Roasted'), ('ground', 'Ground'), ('packaged', 'Packaged')], max_length=30, null=True)),
                ('to_stage', models.CharField(blank=True, choices=[('green_received', 'Green Bean Received'), ('stored', 'Stored'), ('roasted', 'Roasted'), ('ground', 'Ground'), ('packaged', 'Packaged')], max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_shipped_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipped_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('coffee_stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.coffeestock')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.contract')),
            ],
        ),
    ]
