# Generated by Django 6.0.8 on 2026-09-03 14:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('default_coffee_type', models.CharField(choices=[('arabica', 'Arabica'), ('robusta', 'Robusta')], max_length=20)),
                ('default_grade', models.CharField(blank=True, max_length=50)),
                ('default_source', models.CharField(blank=True, max_length=250)),
                ('default_process', models.CharField(blank=True, max_length=50)),
                ('default_foreign_smell', models.CharField(blank=True, default='None', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('is_acquired_client', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_stage', models.CharField(choices=[('new_lead', 'New Lead'), ('sample_sent', 'Sample Sent'), ('sample_received', 'Sample Received'), ('followup', 'Follow-up'), ('negotiation', 'Negotiation'), ('contract_signed', 'Contract Signed'), ('recurring_supply', 'Recurring Supply'), ('lost', 'Lost')], default='new_lead', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.PositiveIntegerField(choices=[(50, '50g'), (250, '250g'), (500, '500g'), (1000, '1kg'), (15, 'Sachet (15g)')], unique=True)),
                ('label', models.CharField(max_length=30)),
                ('is_sachet', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grams'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'System Admin'), ('SALES', 'Sales Attendant'), ('MANAGER', 'Store Manager'), ('CASHIER', 'Cashier'), ('ACCOUNTS', 'Accounts (Legacy)')], db_index=True, default='SALES', max_length=10)),
                ('contact', models.CharField(blank=True, help_text='Phone contact format: +256700000000', max_length=20, null=True, unique=True)),
                ('employee_id', models.CharField(blank=True, help_text='Unique tracking code', max_length=30, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=20)),
                ('object_id', models.CharField(max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('coffee_type', models.CharField(choices=[('arabica', 'Arabica'), ('robusta', 'Robusta')], max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=250)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('process', models.CharField(blank=True, max_length=50)),
                ('season_of_harvest', models.CharField(blank=True, max_length=100)),
                ('quantity_sorted_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foreign_smell', models.CharField(blank=True, max_length=50)),
                ('foreign_matter', models.CharField(blank=True, max_length=50)),
                ('prints', models.CharField(blank=True, max_length=50)),
                ('physical_damages', models.CharField(blank=True, max_length=50)),
                ('fermentation_type', models.CharField(blank=True, choices=[('aerobic_fermentation', 'Aerobic Fermentation'), ('anaerobic_fermentation', 'Anaerobic Fermentation'), ('natural', 'Natural'), ('other', 'Other')], default='aerobic_fermentation', max_length=50)),
                ('defects', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_after_sorting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=150)),
                ('verified_by', models.CharField(blank=True, max_length=250)),
                ('delivered_by', models.CharField(blank=True, max_length=150)),
                ('car_number', models.CharField(blank=True, max_length=50)),
                ('received_by', models.CharField(blank=True, max_length=150)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='web.coffeevariety')),
            ],
        ),
        migrations.CreateModel(
            name='PackagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('beans', 'Beans'), ('ground', 'Ground')], max_length=10)),
                ('kg_per_pack', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='web.blend')),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='web.packsize')),
            ],
            options={
                'ordering': ['blend__name', 'pack_size__grams', 'form'],
            },
        ),
        migrations.CreateModel(
            name='PackagedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='web.packagedproduct')),
            ],
            options={
                'ordering': ['product__blend__name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_stage', models.CharField(choices=[('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee')], max_length=30)),
                ('input_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packs_produced', models.PositiveIntegerField(blank=True, null=True)),
                ('coffee_used_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loss_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('open', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_runs_completed', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_runs_issued', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_runs', to='web.packagedproduct')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_runs', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PackRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs_out', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('released', 'Released'), ('partially_returned', 'Partially Returned'), ('fully_returned', 'Fully Returned')], default='released', max_length=30)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_releases_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='web.packagedproduct')),
                ('released_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='PackReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs_returned', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(max_length=150)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_returns_received', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='web.packrelease')),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='PackSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs_sold', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('partial', 'Partially Paid'), ('cleared', 'Cleared')], default='partial', max_length=20)),
                ('cleared_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_settlements', to=settings.AUTH_USER_MODEL)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='web.packrelease')),
            ],
            options={
                'ordering': ['-cleared_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('roasting', 'Roasting'), ('sorting', 'Sorting'), ('grinding', 'Grinding')], max_length=20)),
                ('input_stage', models.CharField(choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30)),
                ('output_stage', models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True)),
                ('input_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('secondary_output_stage', models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True)),
                ('secondary_output_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loss_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('open', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs_completed', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs_issued', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_runs', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RoastedSackSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('kg_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roasted_sack_sales', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sack_sales', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_weight', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='in_transit', max_length=30)),
                ('courier_name', models.CharField(default='DHL', max_length=50)),
                ('tracking_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coffee_stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.coffeestock')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.company')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('day_3_guide_sent_at', models.DateTimeField(blank=True, null=True)),
                ('day_7_contract_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_converted_to_contract', models.BooleanField(default=False)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume_per_cycle_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signed_name', models.CharField(blank=True, max_length=150)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('next_delivery_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.company')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('interested_in_contract', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.sample')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Stock Received'), ('sample', 'Sample Taken'), ('roast_issue', 'Issued for Roasting'), ('roast_return', 'Roasted Coffee Received'), ('sort_input', 'Issued for Sorting'), ('sort_good_output', 'Good Coffee Received'), ('quaker_output', 'Quakers Received'), ('grind_input', 'Issued for Grinding'), ('grind_return', 'Ground Coffee Received'), ('packaging_issue', 'Issued for Packaging'), ('dispatch', 'Dispatched'), ('loss', 'Processing Loss'), ('adjustment', 'Inventory Adjustment')], max_length=30)),
                ('from_stage', models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True)),
                ('to_stage', models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('sale', 'For Sale'), ('display', 'Display'), ('sampling', 'Sampling'), ('event', 'Event'), ('other', 'Other')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='web.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_request_items', to='web.packagedproduct')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.stockrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='packrelease',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='web.stockrequestitem'),
        ),
        migrations.CreateModel(
            name='SupplyFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_shipped_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipped_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('coffee_stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.coffeestock')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.contract')),
            ],
        ),
        migrations.AddConstraint(
            model_name='packagedproduct',
            constraint=models.UniqueConstraint(fields=('blend', 'pack_size', 'form'), name='unique_packaged_product'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='unique_stock_request_product'),
        ),
    ]
