# Generated by Django 6.0.8 on 2026-09-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsize',
            name='grams',
            field=models.PositiveIntegerField(choices=[(50, '50g'), (250, '250g'), (500, '500g'), (1000, '1kg'), (15, 'Sachet (15g)')]),
        ),
        migrations.AddConstraint(
            model_name='packsize',
            constraint=models.UniqueConstraint(fields=('grams', 'is_sachet'), name='unique_pack_size_type'),
        ),
    ]
