# Generated by Django 6.0.8 on 2026-08-30 09:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.PositiveIntegerField(choices=[(50, '50g'), (250, '250g'), (500, '500g'), (1000, '1kg'), (15, 'Sachet (15g)')], unique=True)),
                ('label', models.CharField(max_length=30)),
                ('is_sachet', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grams'],
            },
        ),
        migrations.RemoveField(
            model_name='coffeestock',
            name='stage',
        ),
        migrations.AlterField(
            model_name='coffeestock',
            name='defects',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coffeestock',
            name='fermentation_type',
            field=models.CharField(blank=True, choices=[('aerobic_fermentation', 'Aerobic Fermentation'), ('anaerobic_fermentation', 'Anaerobic Fermentation'), ('natural', 'Natural'), ('other', 'Other')], default='aerobic_fermentation', max_length=50),
        ),
        migrations.AlterField(
            model_name='coffeestock',
            name='physical_damages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coffeestock',
            name='quantity_after_sorting',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coffeestock',
            name='quantity_sorted_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coffeestock',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='from_stage',
            field=models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Stock Received'), ('sample', 'Sample Taken'), ('roast_issue', 'Issued for Roasting'), ('roast_return', 'Roasted Coffee Received'), ('sort_input', 'Issued for Sorting'), ('sort_good_output', 'Good Coffee Received'), ('quaker_output', 'Quakers Received'), ('grind_input', 'Issued for Grinding'), ('grind_return', 'Ground Coffee Received'), ('packaging_issue', 'Issued for Packaging'), ('dispatch', 'Dispatched'), ('loss', 'Processing Loss'), ('adjustment', 'Inventory Adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='to_stage',
            field=models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PackagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('beans', 'Beans'), ('ground', 'Ground')], max_length=10)),
                ('kg_per_pack', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='web.blend')),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='web.packsize')),
            ],
            options={
                'ordering': ['blend__name', 'pack_size__grams', 'form'],
            },
        ),
        migrations.CreateModel(
            name='PackagedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='web.packagedproduct')),
            ],
            options={
                'ordering': ['product__blend__name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_stage', models.CharField(choices=[('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee')], max_length=30)),
                ('input_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packs_produced', models.PositiveIntegerField(blank=True, null=True)),
                ('coffee_used_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loss_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('open', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_runs_completed', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_runs_issued', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_runs', to='web.packagedproduct')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_runs', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PackRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs_out', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('released', 'Released'), ('partially_returned', 'Partially Returned'), ('fully_returned', 'Fully Returned')], default='released', max_length=30)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_releases_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='web.packagedproduct')),
                ('released_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='PackReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs_returned', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_returns_received', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='web.packrelease')),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('roasting', 'Roasting'), ('sorting', 'Sorting'), ('grinding', 'Grinding')], max_length=20)),
                ('input_stage', models.CharField(choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30)),
                ('output_stage', models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True)),
                ('input_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('secondary_output_stage', models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee'), ('quakers', 'Quakers')], max_length=30, null=True)),
                ('secondary_output_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loss_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('open', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs_completed', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs_issued', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_runs', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RoastedSackSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('kg_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roasted_sack_sales', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sack_sales', to='web.coffeestock')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='packagedproduct',
            constraint=models.UniqueConstraint(fields=('blend', 'pack_size', 'form'), name='unique_packaged_product'),
        ),
    ]
