# Generated by Django 5.2.17 on 2026-08-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='dispatch_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
