# Generated by Django 6.0.8 on 2026-08-31 07:19

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_blend_packsize_remove_coffeestock_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packrelease',
            name='price_per_pack',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='packreturn',
            name='notes',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packrelease',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='packreturn',
            name='returned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
