# Generated by Django 6.0.8 on 2026-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_followup_dispatch_alert_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeestock',
            name='quantity_sorted_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='coffeevariety',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
