# Generated by Django 6.0.8 on 2026-09-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_packsize_grams_packsize_unique_pack_size_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packreturn',
            name='condition',
            field=models.CharField(choices=[('good', 'Good / Resalable'), ('damaged', 'Damaged'), ('opened', 'Opened'), ('expired', 'Expired'), ('other', 'Other')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='packreturn',
            name='notes',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
