# Generated by Django 6.0.8 on 2026-09-08 09:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_packreturn_condition_alter_packreturn_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='packreturn',
            name='disposition',
            field=models.CharField(choices=[('accepted', 'Accept'), ('accepted_charged', 'Accept & Charge Agent'), ('refused', 'Refuse'), ('written_off', 'Write Off')], default='accepted', max_length=30),
        ),
        migrations.AlterField(
            model_name='packrelease',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='packreturn',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('account_type', models.CharField(choices=[('field_agent', 'Field Agent'), ('salesperson', 'Salesperson'), ('customer', 'Customer'), ('walk_in', 'Walk-in Customer'), ('other', 'Other')], default='field_agent', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='packrelease',
            name='released_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pack_releases', to='web.accountholder'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='web.packrelease')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
