# Generated by Django 6.0.8 on 2026-09-02 17:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_packrelease_price_per_pack_packreturn_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('SALES', 'Sales Attendant'), ('MANAGER', 'Store Manager'), ('CASHIER', 'Cashier'), ('ACCOUNTS', 'Accounts (Legacy)')], db_index=True, default='SALES', max_length=10),
        ),
        migrations.CreateModel(
            name='PackSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs_sold', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('partial', 'Partially Paid'), ('cleared', 'Cleared')], default='partial', max_length=20)),
                ('cleared_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_settlements', to=settings.AUTH_USER_MODEL)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='web.packrelease')),
            ],
            options={
                'ordering': ['-cleared_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('sale', 'For Sale'), ('display', 'Display'), ('sampling', 'Sampling'), ('event', 'Event'), ('other', 'Other')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='web.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_request_items', to='web.packagedproduct')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.stockrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='packrelease',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='web.stockrequestitem'),
        ),
        migrations.AddConstraint(
            model_name='stockrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='unique_stock_request_product'),
        ),
    ]
