# Generated by Django 6.0.8 on 2026-09-19 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_packreturn_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='account_holder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profile', to='web.accountholder'),
        ),
        migrations.AddField(
            model_name='packrelease',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_releases', to='web.company'),
        ),
        migrations.AddField(
            model_name='packrelease',
            name='purpose',
            field=models.CharField(choices=[('sale', 'For Sale'), ('display', 'Display'), ('sampling', 'Sampling'), ('event', 'Event'), ('field_agent', 'Field Agent Stock'), ('other', 'Other')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='account_holder',
            field=models.ForeignKey(blank=True, help_text='The individual/account responsible for taking and paying for this stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='web.accountholder'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='destination_type',
            field=models.CharField(choices=[('company', 'Company / Supermarket'), ('agent_float', 'Sales Agent Stock / Float'), ('direct_restaurant', 'Direct Restaurant / Café Sale'), ('event_display', 'Event / Exhibition')], default='agent_float', max_length=30),
        ),
        migrations.AlterField(
            model_name='packrelease',
            name='status',
            field=models.CharField(choices=[('released', 'Released'), ('partially_returned', 'Partially Returned'), ('fully_returned', 'Fully Returned'), ('settled', 'Paid / Settled')], default='released', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='purpose',
            field=models.CharField(choices=[('sale', 'For Sale'), ('display', 'Display'), ('sampling', 'Sampling'), ('event', 'Event'), ('field_agent', 'Field Agent Stock'), ('other', 'Other')], default='sale', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='e.g. Oasis Mall Branch, Village Mall Bugolobi, Lugogo Branch', max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='web.company')),
            ],
        ),
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('audited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='web.company')),
            ],
        ),
        migrations.CreateModel(
            name='BranchStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_location', models.CharField(choices=[('shelf', 'Active Display Shelf'), ('backroom', 'Backroom Warehouse')], default='shelf', max_length=20)),
                ('transaction_type', models.CharField(choices=[('delivery', 'Stock Delivered from Nonda Main Warehouse'), ('restock_shelf', 'Moved from Backroom to Display Shelf'), ('audit_sale', 'Confirmed Sold via Audit'), ('shrinkage', 'Damaged / Expired / Missing Stock'), ('return', 'Returned to Nonda Central Warehouse')], max_length=30)),
                ('quantity', models.IntegerField(help_text='+ Quantity added, - Quantity removed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.packagedproduct')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.packrelease')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='web.companybranch')),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.stockaudit')),
            ],
        ),
        migrations.CreateModel(
            name='StockAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(help_text='Quantity system expected based on previous deliveries.')),
                ('actual_physical_count', models.PositiveIntegerField(help_text='Physical count on shelf entered by sales rep.')),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Calculated: Expected minus Actual Physical Count.')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.stockaudit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.packagedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_display_quantity', models.PositiveIntegerField(default=0, help_text='Units currently sitting on the supermarket shelf/display.')),
                ('last_audited_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_inventories', to='web.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_inventories', to='web.packagedproduct')),
            ],
            options={
                'unique_together': {('company', 'product')},
            },
        ),
    ]
