# Generated by Django 6.0.8 on 2026-09-20 00:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_accountholder_email_company_account_holder_and_more'),
    ]

    operations = [
        # 1. Clear old unique constraint FIRST so SQLite _remake_table won't look for 'company'
        migrations.AlterUniqueTogether(
            name='consignmentinventory',
            unique_together=set(),
        ),

        # 2. Alter Model Options
        migrations.AlterModelOptions(
            name='consignmentinventory',
            options={'verbose_name_plural': 'Consignment Inventories'},
        ),

        # 3. Drop old fields now that the constraint is detached
        migrations.RemoveField(
            model_name='consignmentinventory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='consignmentinventory',
            name='current_display_quantity',
        ),
        migrations.RemoveField(
            model_name='stockaudititem',
            name='actual_physical_count',
        ),
        migrations.RemoveField(
            model_name='stockaudititem',
            name='expected_quantity',
        ),

        # 4. Add new fields (including 'branch')
        migrations.AddField(
            model_name='consignmentinventory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignment_inventories', to='web.companybranch'),
        ),
        migrations.AddField(
            model_name='consignmentinventory',
            name='current_backroom_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units sitting in branch store room.'),
        ),
        migrations.AddField(
            model_name='consignmentinventory',
            name='current_shelf_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units sitting on active retail shelf display.'),
        ),
        migrations.AddField(
            model_name='packrelease',
            name='billable_packs',
            field=models.PositiveIntegerField(default=0, help_text='Units that have actually become billable. For normal sales this defaults to packs_out in the property below; for display/consignment this is increased by supermarket audits.'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='web.companybranch'),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='actual_backroom',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='actual_shelf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='expected_backroom',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='expected_shelf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='shrinkage_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Damaged, expired, or missing stock identified during audit'),
        ),

        # 5. Alter Field Options
        migrations.AlterField(
            model_name='stockaudititem',
            name='calculated_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockaudititem',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0, help_text='Calculated units sold: (Expected Total - Actual Total - Shrinkage)'),
        ),
        migrations.AlterField(
            model_name='stockaudititem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),

        # 6. Create New Models
        migrations.CreateModel(
            name='EventExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Blankets & Wine September Edition', max_length=200)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft / Planning'), ('dispatched', 'Stock Dispatched'), ('reconciled', 'Reconciled & Closed')], default='draft', max_length=20)),
                ('total_cash_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_momo_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_events', to='web.accountholder')),
            ],
        ),
        migrations.CreateModel(
            name='EventItemReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField(default=0)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The raw production/purchase cost per pack for margin calculation', max_digits=10)),
                ('quantity_sold_retail', models.PositiveIntegerField(default=0, help_text='Packs sold sealed to retail customers')),
                ('unit_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity_brewed', models.PositiveIntegerField(default=0, help_text='Packs opened for cup sales/brewing')),
                ('cups_sold', models.PositiveIntegerField(default=0, help_text='Total cups sold from brewed packs')),
                ('cup_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity_sampled', models.PositiveIntegerField(default=0, help_text='Packs used for free samples / promo')),
                ('quantity_returned', models.PositiveIntegerField(default=0, help_text='Sealed packs returned back to inventory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.eventexecution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.packagedproduct')),
            ],
        ),

        # 7. Apply the NEW unique constraint LAST
        migrations.AlterUniqueTogether(
            name='consignmentinventory',
            unique_together={('branch', 'product')},
        ),
    ]