# Generated by Django 6.0.8 on 2026-09-20 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_consignmentinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsettlement',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='web.packrelease'),
        ),
    ]
