# Generated by Django 6.0.8 on 2026-09-20 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_packsettlement_release'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packrelease',
            options={},
        ),
        migrations.AddField(
            model_name='packreturn',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packreturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packreturn',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='packreturn',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_approval', max_length=30),
        ),
        migrations.AddField(
            model_name='packreturn',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_returns_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packreturn',
            name='disposition',
            field=models.CharField(choices=[('accepted', 'Accepted Return')], default='accepted', max_length=30),
        ),
    ]
