# Generated by Django 6.0.8 on 2026-09-24 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_packrelease_options_packreturn_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('maintenance', 'Maintenance'), ('salaries', 'Salaries'), ('logistics', 'Logistics & Transport'), ('staff_food', 'Staff Food'), ('others', 'Others')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.now, help_text='Date the expense was incurred')),
                ('notes', models.TextField(blank=True, help_text="Detailed note (Required if category is 'Others')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
