# Generated by Django 6.0.8 on 2026-09-25 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('marketing', 'Marketing'), ('staff', 'Staff Consumption'), ('hospitality', 'Visitor / Hospitality'), ('damage', 'Damages / Spoilage'), ('testing', 'Product Testing'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalStockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues', to='web.internalaccount')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_stock_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalStockIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_stage', models.CharField(blank=True, choices=[('green_received', 'Green Coffee'), ('roasted', 'Roasted Coffee'), ('ground', 'Ground Coffee')], max_length=30, null=True)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packs', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kg for non-packaged coffee or cost per pack for packaged coffee.', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coffee_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_stock_issues', to='web.coffeestock')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.internalstockissue')),
                ('packaged_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_stock_issues', to='web.packagedproduct')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
