# Generated by Django 6.0.8 on 2026-09-29 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_internalaccount_internalstockissue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsettlement',
            name='cleared_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
