# Generated by Django 6.0.8 on 2026-09-30 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_packsettlement_cleared_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentAuditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='packrelease',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='display_releases', to='web.companybranch'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_audits_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_audits_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='status',
            field=models.CharField(choices=[('legacy', 'Legacy — reconciliation required'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='shrinkage_backroom',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='shrinkage_shelf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchstockledger',
            name='transaction_type',
            field=models.CharField(choices=[('delivery', 'Stock Delivered from Nonda Main Warehouse'), ('restock_shelf', 'Moved from Backroom to Display Shelf'), ('audit_sale', 'Confirmed Sold via Audit'), ('shrinkage', 'Damaged / Expired / Missing Stock'), ('return', 'Returned to Nonda Central Warehouse'), ('opening_balance', 'Verified historical opening balance')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='stockaudit',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False), ('status', 'pending_approval')), fields=('branch',), name='consignment_one_pending_audit_per_branch'),
        ),
        migrations.AddField(
            model_name='consignmentauditallocation',
            name='audit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_allocations', to='web.stockaudititem'),
        ),
        migrations.AddField(
            model_name='consignmentauditallocation',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_audit_allocations', to='web.packrelease'),
        ),
        migrations.AddField(
            model_name='consignmentinvoice',
            name='audit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='web.stockaudit'),
        ),
        migrations.AddConstraint(
            model_name='consignmentauditallocation',
            constraint=models.UniqueConstraint(fields=('audit_item', 'release'), name='consignment_unique_audit_release'),
        ),
        migrations.AddConstraint(
            model_name='consignmentauditallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='consignment_alloc_qty_positive'),
        ),
    ]
