# Generated by Django 6.0.8 on 2026-09-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_consignmentauditallocation_consignmentinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to='web.companybranch'),
        ),
    ]
