# Generated by Django 6.0.8 on 2026-10-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_stockrequest_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreceipt',
            old_name='method',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='packsettlement',
            name='status',
            field=models.CharField(choices=[('released', 'Released'), ('partially_returned', 'Partially Returned'), ('fully_returned', 'Fully Returned'), ('settled', 'Paid / Settled')], default='partial', max_length=20),
        ),
    ]
